### PR TITLE
add PCB design files from PCB design branch

### PR DESCRIPTION
**Pull request by aburt2**
Adds PCB design files, no changes to firmware

### CODE REVIEW

**Comment by edumeneses** [comment]
Too many files to review :-)

It's good to have this info on the repo, but it is unclear to me if ok to "redistribute" those datasheets.

**Comment by aburt2** [comment]
What I'll do is remove the datasheets and just add a readme with links to them, all of them are publicly available, will also remove the kicad backup files, will switch this a draft review

**Comment by aburt2** [comment]
@edumeneses removed duplicated files, datasheets are linked in the schematics, once again ready for review

**Comment by edumeneses** [comment]
Great work!

IMO, it is ready to merge. If you think it is needed, we can add a README file to this folder with a one-sentence explanation and relevant links (if you think some datasheet is really important to reference). But this can definitely be done later.

**Review by edumeneses — APPROVED** [review]

**Pull request merged**
